-- 1. MASTER TABLOLAR (Bağımlılığı olmayanlar)
CREATE TABLE profiles (
  id uuid PRIMARY KEY DEFAULT auth.uid(),
  full_name text,
  avatar_url text,
  birth_date date,
  gender text,
  height_cm float,
  weight_kg float,
  activity_level text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE ingredients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text,
  default_unit text,
  calories_per_100g float,
  protein_per_100g float,
  carbs_per_100g float,
  fat_per_100g float
);

CREATE TABLE allergens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text
);

CREATE TABLE diet_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text
);

CREATE TABLE tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text
);

-- 2. REFERANS VE İŞLEM TABLOLARI (Profiles'a bağlı olanlar)
CREATE TABLE recipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  servings int,
  created_by uuid REFERENCES profiles(id),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE food_photos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id),
  photo_url text,
  ai_analysis_status text
);

CREATE TABLE shopping_lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id),
  title text,
  status text
);

-- 3. İLİŞKİ VE DETAY TABLOLARI (En son oluşturulması gerekenler)
CREATE TABLE user_goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id),
  goal_type text,
  daily_calorie_target int,
  is_active boolean DEFAULT true
);

CREATE TABLE meal_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id),
  recipe_id bigint REFERENCES recipes(id),
  photo_id bigint REFERENCES food_photos(id),
  logged_at timestamp with time zone DEFAULT now()
);

CREATE TABLE recipe_ingredients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id bigint REFERENCES recipes(id),
  ingredient_id bigint REFERENCES ingredients(id),
  quantity float,
  unit text
);